[platformio]
src_dir = src

[env:corridor_runner]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed   = 115200
monitor_filters = direct

; Mesmos build_flags do R4BB1T (ST7735 128x160, mesmos pinos)
build_flags =
    -Wl,-z,muldefs
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=131
    -D TFT_HEIGHT=162
    -D TFT_RGB_ORDER=TFT_RGB
    -D ST7735_REDTAB=1
    -D TFT_MISO=-1
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=17
    -D TFT_RST=16
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D CGRAM_OFFSET=1
    -D TFT_X_OFFSET=-50
    -D TFT_Y_OFFSET=0
    -D DISABLE_ALL_LIBRARY_WARNINGS=1

lib_deps =
    bodmer/TFT_eSPI
    SPI
    FS
